export const ROLE_ACTIONS = [
    {name: "dashboard"              ,translate: "داشبورد"                   },
    {name: "companyDashboard"       ,translate: "داشبورد شرکت"              },
    {name: "schedules"              ,translate: "برنامه زمان بندی"          },
    {name: "users"                  ,translate: "مدیریت کاربران"             },
    {name: "roles"                  ,translate: "مدیریت نقش ها"              },
    {name: "companies"              ,translate: "مدیریت شرکت ها"             },
    {name: "deviceTypes"            ,translate: "دستگاه ها"                  },
    {name: "regions"                ,translate: "مدیریت منطقه ها"            },
    {name: "segments"               ,translate: "مدیریت قطعات"               },
    {name: "checklistCategories"    ,translate: "دسته بندی چک لیست ها"      },
    {name: "checklists"             ,translate: "چک لیست ها"                 },
    {name: "units"                  ,translate: "مدیریت واحد ها"             },
    {name: "serviceUsers"           ,translate: "مدیریت سرویسکار ها"         },
    {name: "services"               ,translate: "مدیریت سرویس ها"            },
    {name: "damages"                ,translate: "مدیریت خرابی ها"            },
    {name: "emergencies"            ,translate: "مدیریت امداد ها"            },
    {name: "customers"              ,translate: "مدیریت مشتری ها"            },
    {name: "deals"                  ,translate: "مدیریت قرارداد ها"          },
    {name: "financials"             ,translate: "مدیریت امور مالی"           },
    {name: "dealsArchive"           ,translate: "آرشیو قراردادها"            },
    {name: "liftFieldCategories"    ,translate: "دسته بندی فیلدهای آسانسور" },
    {name: "liftFields"             ,translate: "فیلدهای آسانسور"            },
    {name: "dealPlaceholders"       ,translate: "فیلدهای فرم قرارداد"        },
    {name: "messageTemplates"       ,translate: "مدیریت قالب پیامک ها"       },
    {name: "companyMessageTemplates",translate: "قالب پیامک"                  },
];

export const ACTIONS = {
    dashboard               : "داشبورد"                  ,
    companyDashboard        : "داشبورد شرکت"             ,
    schedules               : "برنامه زمان بندی"         ,
    users                   : "مدیریت کاربران"           ,
    roles                   : "مدیریت نقش ها"            ,
    companies               : "مدیریت شرکت ها"           ,
    deviceTypes             : "دستگاه ها"                ,
    regions                 : "مدیریت منطقه ها"          ,
    segments                : "مدیریت قطعات"             ,
    checklistCategories     : "دسته بندی چک لیست ها"     ,
    checklists              : "چک لیست ها"               ,
    units                   : "مدیریت واحد ها"           ,
    serviceUsers            : "مدیریت سرویسکار ها"       ,
    services                : "مدیریت سرویس ها"          ,
    damages                 : "مدیریت خرابی ها"          ,
    emergencies             : "مدیریت امداد ها"          ,
    customers               : "مدیریت مشتری ها"          ,
    deals                   : "مدیریت قرارداد ها"        ,
    financials              : "مدیریت امور مالی"         ,
    dealsArchive            : "آرشیو قراردادها"          ,
    liftFieldCategories     : "دسته بندی فیلدهای آسانسور",
    liftFields              : "فیلدهای آسانسور"          ,
    dealPlaceholders        : "فیلدهای فرم قرارداد"      ,
    messageTemplates        : "مدیریت قالب پیامک ها"     ,
    companyMessageTemplates : "قالب پیامک"               ,
};